spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neildatabase
    username: postgres
    password: a433rtQe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none