create table tg_user (
   userId INTEGER PRIMARY KEY,
   fullName varchar(255),
   phoneNumber varchar(15),
   role varchar(255) NOT NULL
);

create table service_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) UNIQUE NOT NULL
);

create table service (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) UNIQUE NOT NULL,
    price INTEGER NOT NULL,
    duration INTERVAL NOT NULL,
    category_id INTEGER,
    CONSTRAINT fk_service_category
        FOREIGN KEY (category_id)
        REFERENCES service_category (id)
        ON DELETE SET NULL
);

create table daily_record (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL
);

create table time_slot (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIME NOT NULL,
    daily_id BIGINT,
    userId BIGINT,

    CONSTRAINT fk_daily_record
        FOREIGN KEY (daily_id)
        REFERENCES daily_record (id)
        ON DELETE CASCADE
,
    CONSTRAINT fk_user
        FOREIGN KEY (userId)
        REFERENCES tg_user (userId)
        ON DELETE CASCADE
);

insert into service_category (name) values ('Педикюр');
insert into service_category (name) values ('Маникюр');
insert into service_category (name) values ('Наращивание ногтей');

insert into service (name, price, duration, category_id)
values ('Гигиеническая обработка пальчиков ног без покрытия',
900, interval '1 hour 15 minutes', 1);

insert into service (name, price, duration, category_id)
values ('Гигиеническая обработка пальчиков ног с покрытием гель-лак',
1800, interval '2 hour', 1);

insert into service (name, price, duration, category_id)
values ('Гигиеническая обработка стоп и пальчиков без покрытия',
1800, interval '1 hour 30 minutes', 1);

insert into service (name, price, duration, category_id)
values ('Полная обработка стоп и пальчиков с покрытием гель-лак',
2000, interval '2 hour', 1);

insert into service (name, price, duration, category_id)
values ('Наращивание ногтей до 3, покрытие в один тон',
2000, interval '2 hour 30 minutes', 2);

insert into service (name, price, duration, category_id)
values ('Гигиенический маникюр без покрытия',
800, interval '1 hour 15 minutes', 3);

insert into service (name, price, duration, category_id)
values ('Маникюр с укреплением жестким гелем+покрытием гель-лак однотон',
1700, interval '2 hour', 3);
