create table tg_user (
   userId INTEGER PRIMARY KEY,
   chatId BIGINT NOT NULL,
   messageId INTEGER NOT NULL,
   fullName varchar(255),
   phoneNumber varchar(15),
   role varchar(255) NOT NULL
);

create table service_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) UNIQUE NOT NULL
);

create table service (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) UNIQUE NOT NULL,
    price INTEGER NOT NULL,
    duration INTERVAL NOT NULL,
    category_id INTEGER,
    CONSTRAINT fk_service_category
        FOREIGN KEY (category_id)
        REFERENCES service_category (id)
        ON DELETE SET NULL
);

create table daily_record (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL
);

create table time_slot (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIME NOT NULL,
    daily_id BIGINT,
    userId BIGINT,

    CONSTRAINT fk_daily_record
        FOREIGN KEY (daily_id)
        REFERENCES daily_record (id)
        ON DELETE CASCADE
,
    CONSTRAINT fk_user
        FOREIGN KEY (userId)
        REFERENCES tg_user (userId)
        ON DELETE CASCADE
);
